baseURL = "https://amithc-projects.github.io/aurora-docs/"
relativeURLs = false
languageCode = 'en-us'
title = 'Aurora Design System Documentation'

# 1. Allow Raw HTML in Markdown (Critical for your <button> demos)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# 2. Server Configuration
[server]
  port = 1313


[mediaTypes]
  [mediaTypes."text/css"]
    suffixes = ["css"]

[outputFormats]
  [outputFormats.CSS]
    mediaType = "text/css"
    isPlainText = true
    rel = "stylesheet"

[outputs]
  home = ["HTML"]
  section = ["HTML"]
  page = ["HTML"]

[[menu.main]]
  identifier = "overview"
  name = "Overview"
  weight = 10
  pre = "home"

[[menu.main]]
  identifier = "typography"
  name = "Typography"
  weight = 20
  pre = "text_fields"

[[menu.main]]
  identifier = "components"
  name = "Components"
  weight = 30
  pre = "widgets"

[[menu.main]]
  identifier = "components-simple"
  parent = "components"
  name = "Simple Content"
  weight = 1

[[menu.main]]
  identifier = "navigation"
  name = "Navigation"
  weight = 40
  pre = "explore"

[[menu.main]]
  identifier = "nav-site"
  parent = "navigation"
  name = "Site Navigation"
  weight = 1

[[menu.main]]
  identifier = "nav-page"
  parent = "navigation"
  name = "Page Navigation"
  weight = 2

[[menu.main]]
  identifier = "forms"
  name = "Forms & Input"
  weight = 50
  pre = "dynamic_form"

[[menu.main]]
  identifier = "forms-standard"
  parent = "forms"
  name = "Standard Controls"
  weight = 1

[[menu.main]]
  identifier = "page-layouts"
  name = "Page Layouts"
  weight = 60
  pre = "web"

[[menu.main]]
  identifier = "layout-components"
  name = "Layout Components"
  weight = 70
  pre = "view_compact"

[[menu.main]]
  identifier = "archetypes"
  name = "Archetypes"
  weight = 65
  url = "/archetypes/"
  pre = "auto_awesome_mosaic"

[[menu.main]]
  identifier = "components-molecules"
  parent = "layout-components"
  name = "Molecules"
  weight = 20
  url = "/molecules/"

[[menu.main]]
  identifier = "components-patterns"
  parent = "layout-components"
  name = "Patterns"
  weight = 30
  url = "/patterns/"
